(ns loop-system-dynamics.aca-marketplace-decline
  "A fourth real XMILE instantiation (alongside cloud-itonami's backlog
   drain and etzhayyim's F2 acquisition funnel): a genuinely different
   MODEL SHAPE, `kotoba-lang/dynamics.xmile/percentage-rate-model`
   (proportional/exponential `Stock' = Stock * rate`, not an additive
   inflow), against `aca-marketplace-enrollment` in `dynamics.core/
   loop-archetypes` -- the real 2025->2026 US ACA health-insurance
   marketplace enrollment decline (24.3M -> 23.1M, CMS-reported).

   Reads the two real enrollment figures straight out of `dynamics.core/
   loop-archetypes` (never hardcodes the rate -- if that archetype's real
   figures are ever updated with a newer observation, this projection
   updates with them)."
  (:require ["fs" :as fs]
            ["path" :as path]
            [clojure.string :as str]
            [dynamics.core :as d]
            [dynamics.xmile :as dx]
            [xmile.model :as m]
            [xmile.validate :as validate]
            [xmile.execute :as execute]))

(defn- ensure-dir! [file-path]
  (fs/mkdirSync (path/dirname file-path) #js {:recursive true}))

(def xmile-ns
  {:model m/model :sim-specs m/sim-specs :aux m/aux :flow m/flow
   :stock m/stock :add-variable m/add-variable})

;; ---------------------------------------------------------------------------
;; observe -- pull the real enrollment figures out of the shared archetype catalog
;; ---------------------------------------------------------------------------

(defn observe []
  (let [{:keys [enrollees-2025 enrollees-2026]} (:aca-marketplace-enrollment d/loop-archetypes)]
    (when-not (and enrollees-2025 enrollees-2026)
      (throw (ex-info "aca-marketplace-decline: loop-archetypes is missing the real enrollment figures" {})))
    {:enrollees-2025-millions (/ enrollees-2025 1.0e6)
     :enrollees-2026-millions (/ enrollees-2026 1.0e6)
     :annual-rate (- (/ enrollees-2026 enrollees-2025) 1)}))

;; ---------------------------------------------------------------------------
;; evaluate -- real percentage-rate-model projection
;; ---------------------------------------------------------------------------

(defn evaluate
  [{:keys [enrollees-2025-millions enrollees-2026-millions annual-rate]}
   & [{:keys [sim-years checkpoints half-peak-threshold]
       :or {sim-years 30 checkpoints [1 5 10 20 30]}}]]
  (let [model (dx/percentage-rate-model xmile-ns
                                         {:name "aca-marketplace-decline"
                                          :initial-stock enrollees-2026-millions
                                          :annual-rate annual-rate
                                          :sim-years sim-years})
        valid? (validate/valid? (validate/validate model))
        ;; "half the 2025 PEAK" -- the label and the threshold must agree
        threshold (or half-peak-threshold (/ enrollees-2025-millions 2.0))]
    {:model model
     :valid? valid?
     :projection (when valid? (dx/project execute/run model checkpoints))
     :half-crossing-year (when valid? (dx/crossing-year execute/run model annual-rate threshold))
     :half-threshold-millions threshold}))

;; ---------------------------------------------------------------------------
;; act
;; ---------------------------------------------------------------------------

(defn render-report
  [observation evaluation]
  (str "# ACA marketplace enrollment: real exponential-decline projection\n\n"
       "Generated by kotoba-lang/loop-system-dynamics "
       "(loop-system-dynamics.aca-marketplace-decline). Simulation: "
       "kotoba-lang/org-oasis-open-xmile (OASIS XMILE 1.0, RK4), via "
       "kotoba-lang/dynamics.xmile/percentage-rate-model.\n\n"
       "## Real inputs\n\n"
       "- 2025 enrollment: " (:enrollees-2025-millions observation) "M\n"
       "- 2026 enrollment: " (:enrollees-2026-millions observation) "M\n"
       "- Real observed YoY rate: " (.toFixed (* 100 (:annual-rate observation)) 3) "%\n\n"
       "## Projection (IF this single-year rate persisted -- not a forecast)\n\n"
       "| year | projected enrollment (M) |\n|---|---|\n"
       (str/join "\n"
                             (for [[y v] (sort (get-in evaluation [:projection :checkpoints]))]
                               (str "| " y " | " (.toFixed v 2) " |")))
       "\n\nYears to fall below half the 2025 peak ("
       (.toFixed (:half-threshold-millions evaluation) 2) "M): "
       (if-let [y (:half-crossing-year evaluation)] (str (.toFixed y 1) " years") "never within horizon")
       "\n\n## Caveat\n\n"
       "This projects from a SINGLE real year-over-year observation (one data "
       "point, not a multi-year trend) -- the real rate could revert, worsen, "
       "or a subsidy-policy change could reverse it entirely. This is 'what "
       "the one real number implies if it held', not a prediction.\n"))

(defn act!
  [observation evaluation report-path]
  (ensure-dir! report-path)
  (fs/writeFileSync report-path (render-report observation evaluation))
  report-path)

;; ---------------------------------------------------------------------------
;; record-evidence
;; ---------------------------------------------------------------------------

(defn record-evidence!
  [observation evaluation ledger-path]
  (ensure-dir! ledger-path)
  (let [entry (pr-str {:event/enrollees-2025-millions (:enrollees-2025-millions observation)
                        :event/enrollees-2026-millions (:enrollees-2026-millions observation)
                        :event/annual-rate (:annual-rate observation)
                        :event/valid (:valid? evaluation)
                        :event/projection (get-in evaluation [:projection :checkpoints])
                        :event/half-crossing-year (:half-crossing-year evaluation)})]
    (fs/appendFileSync ledger-path (str entry "\n"))
    entry))

;; ---------------------------------------------------------------------------
;; the cycle
;; ---------------------------------------------------------------------------

(defn run-cycle!
  [{:keys [report-path ledger-path sim-opts]
    :or {report-path "target/aca-marketplace-decline-report.md"
         ledger-path "ledger/aca-marketplace-decline-ledger.edn"}}]
  (let [observation (observe)
        evaluation (evaluate observation sim-opts)]
    (when-not (:valid? evaluation)
      (throw (ex-info "aca-marketplace-decline: model failed XMILE validation" {})))
    (act! observation evaluation report-path)
    (record-evidence! observation evaluation ledger-path)
    {:evaluation evaluation
     :report-path report-path
     :ledger-path ledger-path}))
