(ns loop-system-dynamics.nation-state-military
  "Nation-state military-capability observation entities + dynamics bridge.

  Reads resources/nation-state-military-seed.edn (generated by
  scripts/ingest_nation_state_military.cljs from SIPRI / World Bank / FAS --
  all primary sources, dated+sourced, never fabricated). These are
  OBSERVATION/RISK-ANALYSIS entities (Charter Rider §2(a) WEAPONS AND MILITARY
  is non-applicable: this is analysis of public data about military reality,
  not manufacture/sale/distribution/maintenance of weapons). Safety boundary
  carried in the seed: no offensive targeting / engagement optimization /
  weapons guidance -- scope is budget/personnel/inventory for risk assessment.

  ADR-2607203000 (repo-wide dynamics rule): no entity is categorically out of
  scope -- the seed holds all 193 UN members (+Taiwan); per-entity coverage
  varies by what public sources report (absent stocks == not observed, NOT 0).

  This namespace is the data layer (Phase 1): observe + a bridge that lifts an
  entity's stocks into dynamics.core primitives so leverage-scoring /
  loop-structural-strength can be applied. Full XMILE stock-flow simulation
  (deterrence/escalation loops over time) is Phase 2, documented in the ADR."
  (:require [clojure.edn :as edn]
            [clojure.string :as str]
            ["fs" :as fs]
            [dynamics.core :as dynamics]))

(def default-seed-path "resources/nation-state-military-seed.edn")

(defn- slurp [p] (fs/readFileSync p "utf8"))
(defn- slurp-edn [p] (edn/read-string {:default (fn [_ v] v)} (slurp p)))

(defn observe
  "Read the nation-state military capability seed. Returns today's real,
  dated, sourced data -- never fabricated (see seed header)."
  ([] (observe default-seed-path))
  ([seed-path] (slurp-edn seed-path)))

;; --------------------------------------------------------------------------
;; Stock-key -> human label / unit (for dynamics.core/stock construction)
;; --------------------------------------------------------------------------
(def stock-meta
  {:defense-spending-usd              {:label "Defense spending (current USD)"
                                       :unit "USD"}
   :defense-spending-share-of-gdp-pct {:label "Defense spending, share of GDP"
                                       :unit "percent"}
   :active-military-personnel         {:label "Active military personnel"
                                       :unit "persons"}
   :gdp-usd                           {:label "GDP (current USD)"
                                       :unit "USD"}
   :population                        {:label "Population"
                                       :unit "persons"}
   :nuclear-warheads                  {:label "Nuclear warheads (total inventory est.)"
                                       :unit "warheads"}
   ;; Equipment inventory (GlobalFirepower, :estimate? grade -- aggregator)
   :aircraft-total                    {:label "Aircraft total (GFP)" :unit "aircraft"}
   :fighters                          {:label "Fighter aircraft (GFP)" :unit "aircraft"}
   :helicopters                       {:label "Helicopters (GFP)" :unit "rotorcraft"}
   :tanks                             {:label "Tanks / MBTs (GFP)" :unit "vehicles"}
   :naval-total-assets                {:label "Naval total assets (GFP)" :unit "hulls"}})

(defn entity->dynamics-stocks
  "Lift a seed entity's :stocks into validated dynamics.core/stock maps.
  Stocks absent from the entity are omitted (absent != zero). Each returned
  stock satisfies dynamics.core/stock's precondition (id/value/as-of/source)."
  [entity]
  (for [[k m] (:stocks entity)
        :let [{:keys [label unit]} (stock-meta k)]
        :when (number? (:value m))]
    (dynamics/stock {:id k
                     :label (or label (name k))
                     :value (:value m)
                     :unit (or unit "unitless")
                     :as-of (:as-of m)
                     :source (:source m)})))

(defn budget-procurement-loop
  "A nation's annual defense-budget -> procurement -> capability loop, shaped
  after the :global-fossil-fuel-industry archetype (high self-funding, annual
  capital-allocation cycle). gain is :unmeasured -- we have no measured
  conversion rate from spending to capability-increase, so per ADR-2607203000
  we do NOT fabricate one (a large budget * an unmeasured rate is exactly the
  fabricated expected-value the rule forbids). cycle-time = annual budget."
  [entity]
  (dynamics/loop*
   {:id :nation/budget-procurement-capability
    :kind :reinforcing
    :stocks [:defense-spending-usd :active-military-personnel]
    :flows [:procurement :recruitment]
    :gain :unmeasured
    :cycle-time-days 365
    :reference-archetype :global-fossil-fuel-industry}))

;; --------------------------------------------------------------------------
;; Analysis helpers (pure, over observed data)
;; --------------------------------------------------------------------------
(defn- with-stock [entities k]
  (filter #(get-in % [:stocks k]) entities))

(defn top-by
  "Entities sorted descending by stock k's :value. Nil-safe."
  [observation k & [limit]]
  (let [ranked (sort-by #(get-in % [:stocks k :value]) > (with-stock (:entities observation) k))]
    (if limit (take limit ranked) ranked)))

(defn summary
  "High-level coverage + extremal facts over the seed -- every number here is
  a real sourced datum carried in the seed, no aggregation across entities is
  implied (no fabricated global total)."
  [observation]
  (let [ents (:entities observation)]
    {:entity-count (count ents)
     :un-member-count (count (filter :un-member ents))
     :with-defense-spending (count (with-stock ents :defense-spending-usd))
     :with-personnel (count (with-stock ents :active-military-personnel))
     :with-nuclear (count (with-stock ents :nuclear-warheads))
     :with-equipment (count (with-stock ents :aircraft-total))
     :top-5-spending (->> (top-by observation :defense-spending-usd 5)
                          (map (fn [e] {:iso3 (:iso3 e)
                                        :name (:country-name e)
                                        :usd (get-in e [:stocks :defense-spending-usd :value])
                                        :as-of (get-in e [:stocks :defense-spending-usd :as-of])})))
     :top-5-aircraft (->> (top-by observation :aircraft-total 5)
                          (map (fn [e] {:iso3 (:iso3 e) :name (:country-name e)
                                        :n (get-in e [:stocks :aircraft-total :value])})))
     :top-5-tanks (->> (top-by observation :tanks 5)
                       (map (fn [e] {:iso3 (:iso3 e) :name (:country-name e)
                                     :n (get-in e [:stocks :tanks :value])})))}))

;; --------------------------------------------------------------------------
;; Phase 2: structural loop analysis + Meadows leverage points
;; --------------------------------------------------------------------------

;; Local archetype definitions (NOT added to dynamics.core -- merged locally
;; for comparison only). HONESTY: cycle-time (annual budget) and annual-flow
;; (global military spending, SIPRI) are measured/cited; the coefficient
;; estimates are flagged :estimate?. The arms-race reaction gain (Richardson
;; k) is :unmeasured and is NOT used to drive any integration -- using it
;; would fabricate an escalation forecast (ADR-2607203000).
(def military-archetypes
  {:arms-race-action-reaction
   {:cycle-time-days 365            ;; annual appropriations/budget cycle (structural fact)
    :self-funding-coefficient 0.55  ;; defense-industrial reinvestment + lobbying partially
                                    ;; self-reinforces spending (documented Military-Industrial
                                    ;; Complex dynamic, not a single measured coefficient)
    :instrumentation-completeness 0.4 ;; spending levels measured precisely (SIPRI/IISS), but
                                    ;; the loop's DRIVING conversion (threat->spending, k) is
                                    ;; NOT measured globally
    :friction 0.5                   ;; raising spending needs political will, threat narrative,
                                    ;; legislated budgets
    :annual-flow-usd 2.72e12
    :reaction-gain :unmeasured
    :estimate? true
    :source "SIPRI Yearbook 2025 (global military expenditure ~$2.72T, 2024); Richardson action-reaction arms-race model. Coefficients are structural estimates (:estimate?), not measurements."}

   :deterrence-balancing
   {:cycle-time-days 365
    :self-funding-coefficient 0.3
    :instrumentation-completeness 0.4 ;; capability measured; threat->stability conversion not
    :friction 0.6
    :annual-flow-usd 2.72e12
    :gain :unmeasured
    :estimate? true
    :source "Deterrence-as-balancing-loop characterization; same SIPRI pool. Coefficients :estimate?."}})

(defn structural-comparison
  "Rank the military archetypes alongside dynamics.core's catalog by
  loop-structural-strength."
  []
  (dynamics/compare-archetypes
   (merge dynamics/loop-archetypes military-archetypes)))

;; Meadows-band interventions for RISK REDUCTION (not acquisition). Structural
;; (no pool-size): scored band-weight * tractability. Tractability is an
;; auditable heuristic (dynamics.core/leverage-score docstring), not a
;; measured conversion rate.
(def leverage-interventions
  [{:id :redefine-security-paradigm :band :band/A :tractability 0.10
    :label "Redefine security paradigm (military primacy -> cooperative/human security)"}
   {:id :arms-control-treaties :band :band/B :tractability 0.30
    :label "Arms-control/disarmament treaties (New START successor, TPNW)"}
   {:id :spending-transparency :band :band/B :tractability 0.45
    :label "Universal military-spending transparency (UNROCA + SIPRI-grade reporting)"}
   {:id :nuclear-de-alerting :band :band/C :tractability 0.40
    :label "Nuclear de-alerting (remove launch-on-warning posture)"}
   {:id :confidence-building :band :band/C :tractability 0.35
    :label "Confidence-building measures, hotlines, incident-prevention"}
   {:id :procurement-scrutiny :band :band/D :tractability 0.30
    :label "Add deliberative delay / scrutiny to major procurement decisions"}
   {:id :line-item-cuts :band :band/E :tractability 0.50
    :label "Specific procurement line-item reductions"}])

(defn leverage-ranking
  "Score and rank risk-reduction interventions by Meadows leverage band."
  []
  (dynamics/rank-interventions leverage-interventions))

(defn structural-section
  "Markdown for the report: archetype structural-strength ranking (military vs
  catalog) + Meadows leverage-point ranking for risk reduction. Usable as the
  xmile run-cycle's :structural-fn."
  [_observation _decision]
  (let [ranked (:ranked (structural-comparison))
        mil? #{:arms-race-action-reaction :deterrence-balancing}
        rank-of (fn [k] (first (keep-indexed (fn [i [id _]] (when (= id k) (inc i))) ranked)))]
    (str
     "## Structural loop strength: military archetypes vs the catalog\n\n"
     "`loop-structural-strength` applied uniformly (dynamics.core). The military "
     "loops' rank shows their structural compounding speed relative to other real "
     "loops (fossil-fuel, gambling, derivatives...), independent of their "
     "(unmeasured) reaction gain.\n\n"
     "| rank | archetype | structural-strength |\n|---|---|---|\n"
     (str/join "\n" (for [[i [id score]] (map-indexed vector (take 12 ranked))]
                      (str "| " (inc i) " | " (name id) (if (mil? id) " **(military)**" "")
                           " | " (.toFixed score 2) " |")))
     "\n\n- arms-race rank: **#" (or (rank-of :arms-race-action-reaction) "n/a")
     "**; deterrence rank: **#" (or (rank-of :deterrence-balancing) "n/a")
     "** (of " (count ranked) " ranked).\n"
     "- Both military loops carry :unmeasured reaction gain -- the score reflects "
     "cycle-time/self-funding/instrumentation/friction only, NOT a forecast.\n\n"
     "## Leverage points for risk reduction (Meadows bands)\n\n"
     "score = band-weight x tractability (heuristic). Higher band = deeper systemic leverage.\n\n"
     "| score | band | intervention |\n|---|---|---|\n"
     (str/join "\n" (for [{:keys [base-score band label]} (leverage-ranking)]
                      (str "| " (.toFixed base-score 2) " | " (name band) " | " label " |"))))))
