(ns loop-system-dynamics.nation-state-military
  "Nation-state military-capability observation entities + dynamics bridge.

  Reads resources/nation-state-military-seed.edn (generated by
  scripts/ingest_nation_state_military.cljs from SIPRI / World Bank / FAS --
  all primary sources, dated+sourced, never fabricated). These are
  OBSERVATION/RISK-ANALYSIS entities (Charter Rider §2(a) WEAPONS AND MILITARY
  is non-applicable: this is analysis of public data about military reality,
  not manufacture/sale/distribution/maintenance of weapons). Safety boundary
  carried in the seed: no offensive targeting / engagement optimization /
  weapons guidance -- scope is budget/personnel/inventory for risk assessment.

  ADR-2607203000 (repo-wide dynamics rule): no entity is categorically out of
  scope -- the seed holds all 193 UN members (+Taiwan); per-entity coverage
  varies by what public sources report (absent stocks == not observed, NOT 0).

  This namespace is the data layer (Phase 1): observe + a bridge that lifts an
  entity's stocks into dynamics.core primitives so leverage-scoring /
  loop-structural-strength can be applied. Full XMILE stock-flow simulation
  (deterrence/escalation loops over time) is Phase 2, documented in the ADR."
  (:require [clojure.edn :as edn]
            [clojure.string :as str]
            ["fs" :as fs]
            [dynamics.core :as dynamics]))

(def default-seed-path "resources/nation-state-military-seed.edn")

(defn- slurp [p] (fs/readFileSync p "utf8"))
(defn- slurp-edn [p] (edn/read-string {:default (fn [_ v] v)} (slurp p)))

(defn observe
  "Read the nation-state military capability seed. Returns today's real,
  dated, sourced data -- never fabricated (see seed header)."
  ([] (observe default-seed-path))
  ([seed-path] (slurp-edn seed-path)))

;; --------------------------------------------------------------------------
;; Stock-key -> human label / unit (for dynamics.core/stock construction)
;; --------------------------------------------------------------------------
(def stock-meta
  {:defense-spending-usd              {:label "Defense spending (current USD)"
                                       :unit "USD"}
   :defense-spending-share-of-gdp-pct {:label "Defense spending, share of GDP"
                                       :unit "percent"}
   :active-military-personnel         {:label "Active military personnel"
                                       :unit "persons"}
   :gdp-usd                           {:label "GDP (current USD)"
                                       :unit "USD"}
   :population                        {:label "Population"
                                       :unit "persons"}
   :nuclear-warheads                  {:label "Nuclear warheads (total inventory est.)"
                                       :unit "warheads"}})

(defn entity->dynamics-stocks
  "Lift a seed entity's :stocks into validated dynamics.core/stock maps.
  Stocks absent from the entity are omitted (absent != zero). Each returned
  stock satisfies dynamics.core/stock's precondition (id/value/as-of/source)."
  [entity]
  (for [[k m] (:stocks entity)
        :let [{:keys [label unit]} (stock-meta k)]
        :when (number? (:value m))]
    (dynamics/stock {:id k
                     :label (or label (name k))
                     :value (:value m)
                     :unit (or unit "unitless")
                     :as-of (:as-of m)
                     :source (:source m)})))

(defn budget-procurement-loop
  "A nation's annual defense-budget -> procurement -> capability loop, shaped
  after the :global-fossil-fuel-industry archetype (high self-funding, annual
  capital-allocation cycle). gain is :unmeasured -- we have no measured
  conversion rate from spending to capability-increase, so per ADR-2607203000
  we do NOT fabricate one (a large budget * an unmeasured rate is exactly the
  fabricated expected-value the rule forbids). cycle-time = annual budget."
  [entity]
  (dynamics/loop*
   {:id :nation/budget-procurement-capability
    :kind :reinforcing
    :stocks [:defense-spending-usd :active-military-personnel]
    :flows [:procurement :recruitment]
    :gain :unmeasured
    :cycle-time-days 365
    :reference-archetype :global-fossil-fuel-industry}))

;; --------------------------------------------------------------------------
;; Analysis helpers (pure, over observed data)
;; --------------------------------------------------------------------------
(defn- with-stock [entities k]
  (filter #(get-in % [:stocks k]) entities))

(defn top-by
  "Entities sorted descending by stock k's :value. Nil-safe."
  [observation k & [limit]]
  (let [ranked (sort-by #(get-in % [:stocks k :value]) > (with-stock (:entities observation) k))]
    (if limit (take limit ranked) ranked)))

(defn summary
  "High-level coverage + extremal facts over the seed -- every number here is
  a real sourced datum carried in the seed, no aggregation across entities is
  implied (no fabricated global total)."
  [observation]
  (let [ents (:entities observation)]
    {:entity-count (count ents)
     :un-member-count (count (filter :un-member ents))
     :with-defense-spending (count (with-stock ents :defense-spending-usd))
     :with-personnel (count (with-stock ents :active-military-personnel))
     :with-nuclear (count (with-stock ents :nuclear-warheads))
     :top-5-spending (->> (top-by observation :defense-spending-usd 5)
                          (map (fn [e] {:iso3 (:iso3 e)
                                        :name (:country-name e)
                                        :usd (get-in e [:stocks :defense-spending-usd :value])
                                        :as-of (get-in e [:stocks :defense-spending-usd :as-of])})))}))
